### ISSUE TITLE
description and footer menu are not touching dynamically

### ISSUE THREAD

**Issue by itssimmons** [simmxns/tt-clone#2]
### Actual Behavior
Description panel don't have a dynamical position, as a result of that makes them not collide to the bottom menu
![Error](https://user-images.githubusercontent.com/62354548/152692991-737a96d1-0cf5-4f13-8421-2a70db12fd71.png)

### Expected Behavior
Description panel and the menu bottom must be together no matter what the resolution is

**Comment by simmxns** [comment]
[](url)

**Comment by itssimmons** [comment]
Is not totally solved, in some resolutions breaking it again, it is a problem of the video size

**Comment by itssimmons** [comment]
![issue](https://user-images.githubusercontent.com/62354548/152694733-117fa490-a918-48d2-b42a-af6b687c1845.png)
